apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
    # concurrency: 1
    # tryImportMissing: false
    # useDockerCLI: false
  artifacts:
    - image: abbadanmusa/auth
      context: auth
      docker:
        dockerfile: Dockerfile
        # noCache: false
        # pullParent: false
        # squash: false
      sync:
        manual:
          - src: 'scr/**/*.ts'
            dest: .
    - image: abbadanmusa/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.ts'
            dest: .
    - image: abbadanmusa/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'scr/**/*.ts'
            dest: .
    - image: abbadanmusa/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'scr/**/*.ts'
            dest: .
    - image: abbadanmusa/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'scr/**/*.ts'
            dest: .