name: deploy-auth

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - 'auth/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
    - run: cd auth && docker build -t abbadanmusa/auth .
    - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      env: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - run: docker push abbadanmusa/auth
